# agents/report_generator.py

from datetime import datetime
from typing import List, Optional


class ReportGeneratorAgent:
    """
    Sab agents ka output → Ek clean markdown report.

    Markdown kyun?
    - Human readable
    - Downloadable
    - GitHub pe render hota hai
    - Pandoc se PDF/Word mein convert ho sakta hai
    - Streamlit st.markdown() directly render karta hai
    """

    def generate(
        self,
        schema,
        ambiguities,
        hardened_code: str,
        failures,
        dep_map,
        qa_results: dict | None = None,
        diff_report=None
    ) -> str:

        print("\n📄 Generating report...")

        # Sections list mein banao → join karo
        # Kyun list? Directly string concatenation kyun nahi?
        # List append → O(1)
        # String + String → O(n) har baar (new string banata hai)
        # "\n\n".join() → ek baar efficient join
        sections = []

        sections.append(self._section_header(schema))
        sections.append(self._section_quickstart(schema))
        sections.append(self._section_endpoints(schema))
        sections.append(self._section_gaps(ambiguities))
        sections.append(self._section_execution_order(dep_map))

        if qa_results:
            sections.append(self._section_qa(qa_results))

        sections.append(self._section_hardening(failures))
        sections.append(self._section_code(hardened_code))

        if diff_report:
            sections.append(self._section_diff(diff_report))

        sections.append(self._section_footer(
            schema, ambiguities, failures
        ))

        report = "\n\n".join(sections)

        print(f"✅ Report generated!")
        print(f"   Sections: {len(sections)}")
        print(f"   Characters: {len(report)}")

        return report

    # ─────────────────────────────────────
    # SECTION BUILDERS
    # Har section ek alag method
    # Single Responsibility Principle
    # ─────────────────────────────────────

    def _section_header(self, schema) -> str:
        now = datetime.now().strftime('%B %d, %Y at %H:%M')
        # strftime format codes:
        # %B = Full month name (January)
        # %d = Day (01-31)
        # %Y = 4-digit year (2024)
        # %H = Hour 24-format (00-23)
        # %M = Minutes (00-59)

        return f"""# ⚡ API Integration Brief
## {schema.api_name}

> Generated by **Hermes** — Autonomous API Intelligence Agent
> {now}

---"""

    def _section_quickstart(self, schema) -> str:

        headers_formatted = "\n".join([
            f'    "{k}": "{v}"'
            for k, v in schema.global_headers.items()
        ])

        return f"""## ⚡ Quick Start

| Property | Value |
|---|---|
| **Base URL** | `{schema.base_url}` |
| **Auth Method** | {schema.auth_method} |
| **Rate Limits** | {schema.rate_limits} |
| **Endpoints** | {schema.total_endpoints} |

### Authentication
{schema.auth_instructions or 'See authentication section in docs'}

### Required Headers
````python
headers = {{
{headers_formatted}
}}
```"""
        # Double {{ kyun? }}?
        # f-string mein { } = variable interpolation
        # Literal { } dikhana ho → {{ }}
        # {{ }} → { } in output

    def _section_endpoints(self, schema) -> str:

        lines = ["## 📋 Available Endpoints\n"]

        # Method se group karo
        by_method = {}
        for ep in schema.endpoints:
            by_method.setdefault(ep.method, []).append(ep)
            # setdefault kyun?
            # Agar key exist kare → existing value return karo
            # Agar na kare → default set karo aur return karo
            # Same as:
            # if ep.method not in by_method:
            #     by_method[ep.method] = []
            # by_method[ep.method].append(ep)

        # Defined order mein dikhao
        method_order = ["GET", "POST", "PUT", "PATCH", "DELETE"]

        for method in method_order:
            if method not in by_method:
                continue

            lines.append(f"### {method} Endpoints\n")

            for ep in by_method[method]:
                lines.append(f"#### `{method} {ep.path}`")

                if ep.description:
                    lines.append(f"{ep.description}\n")

                # Parameters table
                if ep.required_params or ep.optional_params:
                    lines.append("| Parameter | Required | Type |")
                    lines.append("|---|---|---|")

                    for param in ep.required_params:
                        ptype = ep.param_types.get(param, "string")
                        lines.append(
                            f"| `{param}` | ✅ Yes | {ptype} |"
                        )

                    for param in ep.optional_params:
                        ptype = ep.param_types.get(param, "string")
                        lines.append(
                            f"| `{param}` | No | {ptype} |"
                        )

                    lines.append("")

                # Error codes
                if ep.error_codes:
                    err_str = ", ".join([
                        f"`{e['code']}`"
                        for e in ep.error_codes[:4]
                        # [:4] → max 4 error codes dikhao
                    ])
                    lines.append(f"**Error codes:** {err_str}\n")

                lines.append("---")

        return "\n".join(lines)

    def _section_gaps(self, ambiguities) -> str:

        if not ambiguities:
            return (
                "## ⚠️ Documentation Gaps\n\n"
                "✅ Documentation is complete — no gaps found!"
            )

        high   = [a for a in ambiguities if a.severity == "high"]
        medium = [a for a in ambiguities if a.severity == "medium"]
        low    = [a for a in ambiguities if a.severity == "low"]

        lines = [
            "## ⚠️ Documentation Gaps\n",
            f"**{len(ambiguities)} gaps found** — "
            f"Hermes made these assumptions:\n"
        ]

        if high:
            lines.append("### 🔴 Critical Gaps\n")
            for a in high:
                lines.append(
                    f"- **`{a.endpoint}`** — {a.description}\n"
                    f"  > Assumption: *{a.assumption_made}*\n"
                )

        if medium:
            lines.append("### 🟡 Medium Gaps\n")
            for a in medium:
                lines.append(
                    f"- **`{a.endpoint}`** — {a.description}\n"
                    f"  > Assumption: *{a.assumption_made}*\n"
                )

        if low:
            lines.append("### 🟢 Minor Gaps\n")
            for a in low:
                lines.append(
                    f"- **`{a.endpoint}`** — {a.description}\n"
                )

        return "\n".join(lines)

    def _section_execution_order(self, dep_map) -> str:

        lines = [
            "## 🔄 Correct Execution Order\n",
            "Call endpoints in this order to avoid dependency errors:\n"
        ]

        for i, path in enumerate(dep_map.execution_order, 1):
            deps = dep_map.dependencies.get(path, [])
            dep_str = (
                f" ← needs `{deps[0]}`" if deps
                else " *(independent)*"
            )
            lines.append(f"{i}. `{path}`{dep_str}")

        if dep_map.has_circular:
            lines.append(
                "\n> ⚠️ Circular dependency was detected "
                "and automatically resolved."
            )

        return "\n".join(lines)

    def _section_qa(self, qa_results: dict) -> str:

        lines = [
            "## 💬 Key API Insights\n",
            "Auto-analyzed from documentation:\n"
        ]

        display_labels = {
            "authentication": "🔐 Authentication",
            "rate_limits":    "⏱️  Rate Limits",
            "pagination":     "📄 Pagination",
            "error_handling": "❌ Error Handling",
            "base_url":       "🌐 Base URL",
        }

        confidence_emoji = {
            "high":   "✅",
            "medium": "🟡",
            "low":    "❓",
            "none":   "❌"
        }

        for key, result in qa_results.items():
            label = display_labels.get(key, key.replace("_"," ").title())
            # .title() → "error handling" → "Error Handling"
            # .replace("_"," ") → "error_handling" → "error handling"
            emoji = confidence_emoji.get(result.confidence, "❓")

            lines.append(f"### {label} {emoji}\n")
            lines.append(f"{result.answer}\n")

            if result.source_sections:
                sections_str = ", ".join(result.source_sections)
                lines.append(f"*Source: `{sections_str}`*\n")

        return "\n".join(lines)

    def _section_hardening(self, failures) -> str:

        if not failures:
            return (
                "## 🛡️ Code Reliability\n\n"
                "✅ **Code passed all 7 adversarial tests!**\n"
                "No additional hardening was required."
            )

        lines = [
            "## 🛡️ Vulnerabilities Fixed\n",
            f"**{len(failures)} issues** found and fixed "
            f"automatically:\n"
        ]

        severity_emoji = {
            "critical": "🔴",
            "high":     "🟠",
            "medium":   "🟡"
        }

        for f in failures:
            emoji = severity_emoji.get(f.severity, "⚪")
            lines.append(
                f"- {emoji} **{f.attack_type}** — Fixed\n"
                f"  Was missing: {f.code_gap}\n"
            )

        lines.append(
            "\nAll fixes applied. Code is production-ready."
        )

        return "\n".join(lines)

    def _section_code(self, code: str) -> str:
        line_count = len(code.splitlines())
        return (
            f"## 💻 Production-Ready Code\n\n"
            f"*{line_count} lines — hardened against "
            f"7 production failure patterns*\n\n"
            f"```python\n{code}\n```"
        )

    def _section_diff(self, diff_report) -> str:

        lines = [
            f"## 🔄 Version Comparison\n",
            f"**{diff_report.v1_label}** vs "
            f"**{diff_report.v2_label}** — "
            f"{diff_report.total_changes} total changes\n"
        ]

        if diff_report.breaking_changes:
            lines.append(
                f"### 🔴 Breaking Changes "
                f"({len(diff_report.breaking_changes)})\n"
            )
            for c in diff_report.breaking_changes:
                lines.append(
                    f"- **{c.endpoint}**: {c.description}\n"
                    f"  *Fix: {c.migration_hint}*\n"
                )

        if diff_report.new_features:
            lines.append(
                f"### 🟢 New Features "
                f"({len(diff_report.new_features)})\n"
            )
            for f in diff_report.new_features:
                lines.append(f"- `{f.endpoint}`: {f.description}\n")

        lines.append(
            f"\n### Migration Guide\n{diff_report.migration_guide}"
        )

        return "\n".join(lines)

    def _section_footer(
        self, schema, ambiguities, failures
    ) -> str:
        return f"""---
        ## 📊 Summary

| Metric | Value |
|---|---|
| Endpoints Analyzed | {schema.total_endpoints} |
| Documentation Gaps | {len(ambiguities)} |
| Adversarial Tests | 7 |
| Vulnerabilities Fixed | {len(failures)} |
| Code Status | ✅ Production Ready |

---
*Generated by Hermes — Autonomous API Intelligence Agent*
*LangChain + LangGraph + ChromaDB + GPT-4o*"""